// ********RoostGPT********
// Test generated by RoostGPT for test ReactTesting using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
// Assuming Jest and React Testing Library are already set up in this project

import React from 'react';
import { render, screen } from '@testing-library/react';
import { Route } from 'react-router-dom';
import { MemoryRouter } from 'react-router';
import App from '../../App';

// Creating a mock components for routes to isolate test environment
jest.mock('../Birthday', () => {
  return {
    __esModule: true,
    default: () => <div data-testid="mock-birthday">Mock Birthday Component</div>,
  };
});

jest.mock('../RouterBirthday', () => {
  return {
    __esModule: true,
    default: () => <div data-testid="mock-router-birthday">Mock RouterBirthday Component</div>,
  };
});

jest.mock('../Generate', () => {
  return {
    __esModule: true,
    default: () => <div data-testid="mock-generate">Mock Generate Component</div>,
  };
});

describe('App', () => {
  test('renders Birthday component for root path', () => {
    render(
      <MemoryRouter initialEntries={['/']}>
        <App />
      </MemoryRouter>
    );
    expect(screen.getByTestId('mock-birthday')).toBeInTheDocument();
  });

  test('renders RouterBirthday component for birthday path', () => {
    render(
      <MemoryRouter initialEntries={['/birthday/John/1/1']}>
        <App />
      </MemoryRouter>
    );
    expect(screen.getByTestId('mock-router-birthday')).toBeInTheDocument();
  });

  test('renders Generate component for generate path', () => {
    render(
      <MemoryRouter initialEntries={['/generate']}>
        <App />
      </MemoryRouter>
    );
    expect(screen.getByTestId('mock-generate')).toBeInTheDocument();
  });
});

