// ********RoostGPT********
// Test generated by RoostGPT for test ReactTesting using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
import React, { useState, useEffect } from 'react';
import PropTypes from 'prop-types';

const Countdown = ({ startCount }) => {
  const [count, setCount] = useState(startCount);

  useEffect(() => {
    if (count > 0) {
      const timerId = setTimeout(() => setCount(count - 1), 1000);
      return () => clearTimeout(timerId);
    }
  }, [count]);

  return (
    <div data-test-id="countdown">
      {count > 0 ? count : 'Time is up!'}
    </div>
  );
};

Countdown.propTypes = {
  startCount: PropTypes.number.isRequired,
};

export default Countdown;

