// ********RoostGPT********
// Test generated by RoostGPT for test ReactTesting123 using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
import React from 'react';
import { render, cleanup, fireEvent,screen } from '@testing-library/react';
import '@testing-library/jest-dom/extend-expect';
import Wish from '../../Wish.jsx';

describe('Wish component', () => {
  // Perform general setup if necessary
  beforeEach(() => {
    // Setup tasks before each test
  });

  afterEach(cleanup); // Cleanup tasks after each test

  test('renders without crashing', () => {
    const name ="Bhhavya!";
    const { getByTestId } = render(<Wish name={name} />);
    // Assert that the component mounted
    const container = screen.getByText(/HAPPY BIRTHDAY/);
  expect(container).toBeInTheDocument();
    // expect(getByTestId('wish-message')).toBeInTheDocument();
  });

  test('displays the correct initial message', () => {
    const name ="Bhhavya!";
    const { getByText } = render(<Wish name={name} />);
    // Assert the initial message prop is displayed
    expect(getByText("BHHAVYA!")).toBeInTheDocument();
  });

  // Add more test cases here...

});

