// ********RoostGPT********
// Test generated by RoostGPT for test ReactTesting using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
import React from 'react';
import { render, screen } from '@testing-library/react';
import Wish from '../../Wish.jsx';

// Test suite for the Wish component
describe('Wish', () => {
  // Test case to check if the component renders a wish message with the passed name
  test('renders a birthday wish with the name', () => {
    const name = 'Jane';
    render(<Wish name={name} />);
    const wishMessage = screen.getByText(`HAPPY BIRTHDAY ${name.toUpperCase()} !!!`, { selector: '.wish-message .highlight' });
    expect(wishMessage).toBeInTheDocument();
  });

  // Test case to check if the component renders the name in uppercase
  test('renders the name in uppercase', () => {
    const name = 'John';
    render(<Wish name={name} />);
    const renderedName = screen.getByText(name.toUpperCase());
    expect(renderedName).toBeInTheDocument();
    expect(renderedName).toHaveClass('highlight');
  });

  // Test case to check if the component renders correctly with an empty name
  test('renders correctly with an empty name', () => {
    render(<Wish name="" />);
    const wishMessage = screen.getByText('HAPPY BIRTHDAY  !!!', { selector: '.wish-message' });
    expect(wishMessage).toBeInTheDocument();
    expect(wishMessage).toContainHTML('<span class="highlight"></span>');
  });

  // Additional test cases can be added here for different scenarios
});

