// ********RoostGPT********
// Test generated by RoostGPT for test ReactTest using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
// Import statements
import React from 'react';
import { render } from '@testing-library/react';
import Wish from '../src/Wish';

// Test suite for the Wish component
describe('Wish component', () => {
  test('renders with non-empty name', () => {
    const { getByText } = render(<Wish name="John" />);
    expect(getByText(/HAPPY BIRTHDAY JOHN/i)).toBeInTheDocument();
  });

  test('renders with empty name', () => {
    const { getByText } = render(<Wish name="" />);
    expect(getByText(/HAPPY BIRTHDAY/i)).toBeInTheDocument();
  });

  test('transforms name to uppercase', () => {
    const { getByText } = render(<Wish name="Jane" />);
    expect(getByText(/JANE/).className).toBe('highlight');
  });
});

